version = "3.10.0"
runner.dialect = scala212
fileOverride {
  "glob:**/apps/jvm/src/main/scala/**" {
     runner.dialect = scala3
  }
  "glob:**/../../../../.sbt/1.0/staging/24458e643a75b5ab1472/webapp-lib/js/src/main/scala/**" {
     runner.dialect = scala3
  }
  "glob:**/../../../../.sbt/1.0/staging/24458e643a75b5ab1472/webapp-lib/jvm/src/test/scala/**" {
     runner.dialect = scala3
  }
  "glob:**/apps/shared/src/main/scala/**" {
     runner.dialect = scala3
  }
  "glob:**/../../../../.sbt/1.0/staging/24458e643a75b5ab1472/webapp-lib/shared/src/main/scala/**" {
     runner.dialect = scala3
  }
  "glob:**/apps/js/src/main/scala/**" {
     runner.dialect = scala3
  }
  "glob:**/../../../../.sbt/1.0/staging/24458e643a75b5ab1472/webapp-lib/jvm/src/main/scala/**" {
     runner.dialect = scala3
  }
}
